name: Push to Org-id.guide
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      name: Pull repo
      with:
        repository: org-id/register
        path: orgid_repo
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - uses: actions/cache@v4
      name: Cache dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate latest data
      run: |
        cp -r static docs
        python scraper.py --refresh
    - name: Update Org ID with latest gov-id-finder country data
      run: |
        python update_org_id_guide.py
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.TOKEN }}
        path: orgid_repo
        commit-message: Org-ID update from gov-id-finder-data
        committer: CodeforIATI bot <57559326+codeforIATIbot@users.noreply.github.com>
        author: CodeforIATI bot <57559326+codeforIATIbot@users.noreply.github.com>
        branch: gov-id-update
        delete-branch: true
        title: COA codelists update
        body: Codelist update, sent from [this GitHub Action build](https://github.com/codeforIATI/gov-id-finder-data/actions/runs/${{ github.run_id }}).
